export type Language = 'en' | 'fr'

export const profile = {
  name: 'Walid Maarad',
  initials: 'WM',
  company: 'Intelcia Software Solutions',
  linkedin: 'https://www.linkedin.com/in/walidmaarad/',
  github: 'https://github.com/walsam',
  email: 'mailto:wmaarad@gmail.com',
}

const shared = {
  tags: {
    backend: ['Java', 'Spring Boot', 'Symfony', 'Laravel'],
    frontend: ['React', 'Angular', 'JavaScript', 'React Native', 'Flutter', 'Sass'],
    delivery: ['MySQL', 'Oracle', 'SQL Server', 'Docker', 'GitLab', 'Git', 'Jira'],
    architecture: ['Microservices', 'REST APIs', 'SOAP', 'UML', 'Merise', 'Code review'],
  },
}

export const translations = {
  en: {
    documentTitle: 'Walid Maarad — Technical Lead',
    documentDescription: 'Walid Maarad — technical lead building public platforms, travel products, and payment journeys.',
    skip: 'Skip to content',
    homeLabel: 'Walid Maarad, home',
    menu: 'Menu',
    close: 'Close',
    themeSystem: 'Theme follows device settings. Activate to select the light theme.',
    themeLight: 'Light theme selected. Activate to select the dark theme.',
    themeDark: 'Dark theme selected. Activate to follow device settings.',
    languageSwitchLabel: 'Switch to French',
    primaryNavigationLabel: 'Primary navigation',
    profileDetailsLabel: 'Profile details',
    nav: { about: 'About', journey: 'Journey', projects: 'Projects', toolkit: 'Toolkit', lab: 'Lab', contact: 'Contact' },
    availability: 'Open to meaningful conversations',
    role: 'Technical Lead · Technical Referent',
    location: 'Rabat, Morocco',
    hero: {
      before: 'Technical lead working confidently across',
      emphasis: 'architecture, delivery,',
      after: 'and team leadership.',
      explore: 'Explore',
      exploreLabel: 'Explore my work',
      meta: 'Java · React · Leadership',
    },
    about: {
      label: 'About',
      eyebrow: 'A builder at heart',
      titleBefore: 'From writing features to leading',
      titleAccent: 'systems',
      titleAfter: ', teams, and change.',
      paragraphs: [
        'I started as a full-stack engineer delivering public services for Moroccan citizens, then moved through private-sector and travel projects before growing into technical leadership at Intelcia Software Solutions.',
        'Today, I lead teams of 5 to 15 engineers, design software architectures, produce project estimates, review merge requests, and remain close enough to the code to solve complex problems alongside the team.',
      ],
    },
    work: {
      label: 'Work',
      eyebrow: 'One employer · evolving client contexts',
      title: 'Comfortable with change. Accountable for delivery.',
    },
    careerStages: [
      {
        period: 'Current client context', client: 'AB · Karavel Group', title: 'Technical Lead · Technical Referent',
        summary: 'Leading the technical direction of cruise products, from the public-facing website to B2C and B2B booking, checkout, and payment flows.',
        details: [
          'Integrated Monext and FLOA payment services to support payment in full and two- or four-installment plans.',
          'Own architecture decisions, merge-request reviews, delivery estimates, and technical coordination.',
          'Work across customer-facing flows where reliability, security, and conversion all matter.',
        ],
        tags: ['Spring Boot', 'React', 'Payments', 'REST', 'SOAP'],
      },
      {
        period: 'Technical Lead since May 2023', client: 'Karavel', title: 'Technical Lead',
        summary: 'Progressed from full-stack development to leading multiple travel-platform initiatives.',
        details: [
          'Led teams ranging from 5 to 15 engineers across concurrent projects.',
          'Managed project estimates, commercial proposals, software architecture, code reviews, and delivery planning.',
          'Modernized Promovacances, Promocroisière, and FRAM applications while preserving existing business functionality.',
        ],
        tags: ['Java', 'Spring Boot', 'React', 'Architecture', 'Leadership'],
      },
      {
        period: 'Jan 2021 — Apr 2023', client: 'Public & private sector', title: 'Software Engineer',
        summary: 'Delivered web and mobile platforms for national public services, ministries, public entities, and private-sector clients.',
        details: [
          'Contributed to public-service portals for Morocco’s Digital Development Agency (ADD), including Watiqa, Chikaya, and Mawiidi.',
          'Built a mobile application for the Ministry of Justice.',
          'Contributed to other platforms for TMSA, Tanger Med West, MCJS, and additional public entities.',
          'Later delivered solutions in private-client contexts including RADEES and inwi.',
        ],
        tags: ['Spring', 'Symfony', 'Laravel', 'Angular', 'React Native'],
      },
    ],
    projectsSection: {
      label: 'Selected work', eyebrow: 'Platforms with real users',
      title: 'Across public service, travel, and payments.',
      note: 'Some work is subject to client confidentiality obligations. Descriptions focus on public context, responsibilities, and technologies.',
    },
    projects: [
      { index: '01', category: 'Travel · Commerce', title: 'Cruise booking & payment', client: 'AB · Promocroisière', copy: 'B2C and B2B booking and checkout flows, with single-payment and two- or four-installment options integrated through Monext and FLOA.', tags: ['B2C / B2B', 'Monext', 'FLOA', '2x / 4x payments'] },
      { index: '02', category: 'Travel · Modernization', title: 'Promovacances · FRAM · Promocroisière', client: 'Karavel', copy: 'Modernization of high-traffic tourism platforms while preserving their mature features and existing dependencies.', tags: ['Spring Boot', 'React', 'Sass', 'REST / SOAP'] },
      { index: '03', category: 'GovTech · Mobile', title: 'Criminal Record Request App', client: 'Ministry of Justice', copy: 'A mobile service enabling citizens to request an official criminal-record extract online from Moroccan courts.', tags: ['React Native', 'Java', 'Swift'] },
      { index: '04', category: 'GovTech · Platforms', title: 'Citizen-facing public services', client: 'ADD & public entities', copy: 'Contributions to Watiqa, Chikaya, Mawiidi, the e-procurement and Auto-Entrepreneur platforms, and other institutional services.', tags: ['Symfony', 'Angular', 'Flowable', 'MySQL'] },
    ],
    toolkit: {
      label: 'Toolkit', eyebrow: 'Depth and range', title: 'Technical enough to build. Broad enough to lead.',
      leadershipLabel: 'Leadership scope', educationLabel: 'Education',
      educationTitle: 'Built on a strong systems foundation.', communityLabel: 'Community',
    },
    principles: [
      { number: '01', title: 'Make complexity feel calm.', copy: 'I like systems that are rigorous underneath and simple where people touch them.' },
      { number: '02', title: 'Build for the real world.', copy: 'Useful software survives changing requirements, imperfect data, and the pressure of production.' },
      { number: '03', title: 'Care past the handoff.', copy: 'Quality is not a final polish. It shapes how a product is designed, shipped, and maintained.' },
    ],
    capabilities: ['Software architecture', 'Team leadership', 'Project estimation', 'Merge-request reviews', 'Client communication', 'Payment integrations'],
    skillGroups: [
      { label: 'Backend', items: shared.tags.backend },
      { label: 'Frontend & mobile', items: shared.tags.frontend },
      { label: 'Databases & delivery tooling', items: shared.tags.delivery },
      { label: 'Architecture & integration', items: shared.tags.architecture },
    ],
    education: [
      { year: '2018 — 2020', degree: 'Specialized Master’s Degree · Information Systems Engineering', school: 'Faculty of Sciences Semlalia · Cadi Ayyad University, Marrakech' },
      { year: '2017 — 2018', degree: 'Professional Bachelor’s Degree · Computer Science', school: 'École Supérieure de Technologie · Mohammed I University, Oujda' },
      { year: '2015 — 2017', degree: 'DUT · Software Application Development', school: 'École Supérieure de Technologie · Mohammed I University, Oujda' },
    ],
    community: [
      { name: 'ForLoop Africa', role: 'Co-organizer', period: '2018 — 2022' },
      { name: 'Enactus', role: 'Member', period: '2015 — 2018' },
    ],
    lab: {
      label: 'Tech Lead Lab',
      eyebrow: 'Decisions in motion',
      title: 'See how I turn ambiguity into a delivery path.',
      intro: 'Interactive decision flows based on the work behind the code: framing risk, choosing boundaries, aligning teams, and shipping progressively.',
      status: 'Live scenario',
      run: 'Run decision flow',
      decisionLabel: 'Architecture decision',
      tradeoffLabel: 'Trade-off',
      leadMoveLabel: 'Tech lead move',
      scenarios: [
        {
          id: 'payments',
          tab: 'Payment orchestration',
          title: 'Design a resilient payment journey',
          brief: 'Add payment in full, 2x, and 4x without coupling checkout to individual providers.',
          nodes: ['B2C / B2B', 'Checkout', 'Payment contract', 'Monext / FLOA', 'Order confirmed'],
          decision: 'Isolate provider-specific logic behind a stable payment-orchestration contract.',
          tradeoff: 'More integration work upfront, but provider changes and failure handling remain contained.',
          leadMove: 'Align product, security, finance, and engineering on retry, cancellation, and refund paths before implementation.',
        },
        {
          id: 'modernization',
          tab: 'Legacy modernization',
          title: 'Modernize without breaking revenue',
          brief: 'Evolve mature travel platforms while preserving critical business behavior and integrations.',
          nodes: ['Legacy journeys', 'Compatibility API', 'Modern UI', 'Domain services', 'Progressive rollout'],
          decision: 'Modernize journey by journey using clear compatibility boundaries instead of a high-risk rewrite.',
          tradeoff: 'Temporary coexistence adds complexity; contracts, monitoring, and ownership keep it manageable.',
          leadMove: 'Sequence delivery slices, define ownership, and protect business continuity with explicit rollout checkpoints.',
        },
        {
          id: 'teams',
          tab: 'Team-scale delivery',
          title: 'Keep 5–15 engineers aligned',
          brief: 'Turn a project estimate and architecture into parallel work without losing technical coherence.',
          nodes: ['Product brief', 'Decision record', 'Squad ownership', 'Review gate', 'Staged release'],
          decision: 'Express the architecture as clear boundaries, contracts, and ownership that teams can execute independently.',
          tradeoff: 'Upfront alignment takes time, but reduces rework, review bottlenecks, and cross-team surprises.',
          leadMove: 'Set review standards, delegate local decisions, track dependencies, and keep feedback loops short.',
        },
      ],
      ai: {
        mark: 'AI',
        eyebrow: 'AI-assisted engineering',
        title: 'Keeping the lead role human, while putting AI to work.',
        copy: 'I keep up with tools such as OpenAI Codex and Claude to explore architecture options, accelerate documentation, prepare reviews, and remove repetitive work. Their output still goes through system context, security checks, tests, and human engineering judgment.',
        tags: ['OpenAI Codex', 'Claude', 'Architecture exploration', 'Review assistance', 'Documentation'],
      },
    },
    contact: {
      orbit: 'LET’S TALK · LET’S BUILD · LET’S TALK ·', eyebrow: 'The next good conversation',
      titleBefore: 'Have something', titleAccent: 'interesting', titleAfter: 'in mind?',
      copy: 'Tell me about the problem you’re trying to solve, the team you’re building, or simply say hello.',
      linkedin: 'Connect on LinkedIn', email: 'Email me',
    },
    footer: { statementOne: 'Thoughtful engineering.', statementTwo: 'Dependable products.', backToTop: 'Back to top ↑' },
  },
  fr: {
    documentTitle: 'Walid Maarad — Lead technique',
    documentDescription: 'Walid Maarad — lead technique spécialisé dans les plateformes publiques, les produits touristiques et les parcours de paiement.',
    skip: 'Aller au contenu',
    homeLabel: 'Walid Maarad, accueil',
    menu: 'Menu',
    close: 'Fermer',
    themeSystem: 'Le thème suit les réglages de l’appareil. Activer pour sélectionner le thème clair.',
    themeLight: 'Thème clair sélectionné. Activer pour sélectionner le thème sombre.',
    themeDark: 'Thème sombre sélectionné. Activer pour suivre les réglages de l’appareil.',
    languageSwitchLabel: 'Passer en anglais',
    primaryNavigationLabel: 'Navigation principale',
    profileDetailsLabel: 'Informations du profil',
    nav: { about: 'À propos', journey: 'Parcours', projects: 'Projets', toolkit: 'Compétences', lab: 'Lab', contact: 'Contact' },
    availability: 'Ouvert aux échanges qui ont du sens',
    role: 'Tech Lead · Référent technique',
    location: 'Rabat, Maroc',
    hero: {
      before: 'Tech Lead, à l’aise entre',
      emphasis: 'architecture, livraison',
      after: 'et leadership d’équipe.',
      explore: 'Explorer',
      exploreLabel: 'Découvrir mon parcours',
      meta: 'Java · React · Leadership',
    },
    about: {
      label: 'À propos', eyebrow: 'Bâtisseur dans l’âme',
      titleBefore: 'Du développement de fonctionnalités au pilotage de', titleAccent: 'systèmes', titleAfter: ', d’équipes et du changement.',
      paragraphs: [
        'J’ai commencé comme développeur full-stack sur des services publics destinés aux citoyens marocains, avant d’évoluer dans des contextes privés et touristiques, puis vers le leadership technique chez Intelcia Software Solutions.',
        'Aujourd’hui, j’encadre des équipes de 5 à 15 personnes, je conçois des architectures, réalise des chiffrages, relis les merge requests et reste suffisamment proche du code pour résoudre les sujets complexes avec l’équipe.',
      ],
    },
    work: { label: 'Parcours', eyebrow: 'Un employeur · des contextes clients variés', title: 'À l’aise avec le changement. Garant de la livraison.' },
    careerStages: [
      {
        period: 'Contexte client actuel', client: 'AB · Groupe Karavel', title: 'Tech Lead · Référent technique',
        summary: 'Pilotage technique des produits dédiés aux croisières, du site vitrine aux parcours de réservation et de paiement B2C et B2B.',
        details: [
          'Intégration des services de paiement Monext et FLOA pour les paiements en une fois, en 2 fois ou en 4 fois.',
          'Responsable des choix d’architecture, des revues de merge requests, des chiffrages et de la coordination technique.',
          'Intervention sur des parcours clients où la fiabilité, la sécurité et la conversion sont essentielles.',
        ],
        tags: ['Spring Boot', 'React', 'Paiement', 'REST', 'SOAP'],
      },
      {
        period: 'Tech Lead depuis mai 2023', client: 'Karavel', title: 'Tech Lead',
        summary: 'Évolution du développement full-stack vers le pilotage de plusieurs projets dans le tourisme et les séjours.',
        details: [
          'Encadrement d’équipes de 5 à 15 ingénieurs sur plusieurs projets menés en parallèle.',
          'Prise en charge des chiffrages, devis, architectures, revues de code et de la planification des livraisons.',
          'Modernisation des applications Promovacances, Promocroisière et FRAM en préservant leurs fonctionnalités métier existantes.',
        ],
        tags: ['Java', 'Spring Boot', 'React', 'Architecture', 'Leadership'],
      },
      {
        period: 'Janv. 2021 — avr. 2023', client: 'Secteurs public & privé', title: 'Ingénieur logiciel',
        summary: 'Conception de plateformes web et mobiles pour des services publics nationaux, ministères, organismes publics et clients privés.',
        details: [
          'Contribution aux portails publics de l’ADD, notamment Watiqa, Chikaya et Mawiidi.',
          'Développement d’une application mobile pour le ministère de la Justice.',
          'Contribution à d’autres plateformes pour TMSA, Tanger Med West, MCJS et d’autres organismes publics.',
          'Puis réalisation de solutions pour des clients privés, dont RADEES et inwi.',
        ],
        tags: ['Spring', 'Symfony', 'Laravel', 'Angular', 'React Native'],
      },
    ],
    projectsSection: {
      label: 'Réalisations', eyebrow: 'Des plateformes pour de vrais utilisateurs', title: 'Service public, tourisme et paiement.',
      note: 'Certains travaux sont soumis à la confidentialité client. Les descriptions se limitent au contexte public, aux responsabilités et aux technologies.',
    },
    projects: [
      { index: '01', category: 'Tourisme · Commerce', title: 'Réservation & paiement croisière', client: 'AB · Promocroisière', copy: 'Parcours de réservation et de paiement B2C et B2B, avec paiement en une fois, en 2 fois ou en 4 fois via Monext et FLOA.', tags: ['B2C / B2B', 'Monext', 'FLOA', 'Paiement 2x / 4x'] },
      { index: '02', category: 'Tourisme · Modernisation', title: 'Promovacances · FRAM · Promocroisière', client: 'Karavel', copy: 'Modernisation de plateformes touristiques à fort trafic, sans perdre les fonctionnalités métier et dépendances déjà en place.', tags: ['Spring Boot', 'React', 'Sass', 'REST / SOAP'] },
      { index: '03', category: 'GovTech · Mobile', title: 'Application mobile de demande de casier judiciaire', client: 'Ministère de la Justice', copy: 'Un service mobile permettant aux citoyens de demander en ligne un extrait officiel du casier judiciaire auprès des tribunaux marocains.', tags: ['React Native', 'Java', 'Swift'] },
      { index: '04', category: 'GovTech · Plateformes', title: 'Services publics numériques', client: 'ADD & organismes publics', copy: 'Contributions à Watiqa, Chikaya, Mawiidi, aux plateformes e-procurement et Auto-Entrepreneur, ainsi qu’à d’autres services institutionnels.', tags: ['Symfony', 'Angular', 'Flowable', 'MySQL'] },
    ],
    toolkit: {
      label: 'Compétences', eyebrow: 'Expertise et polyvalence', title: 'Assez technique pour construire. Une vision assez large pour piloter.',
      leadershipLabel: 'Responsabilités techniques et managériales', educationLabel: 'Formation', educationTitle: 'Une solide base en ingénierie des systèmes.', communityLabel: 'Communauté',
    },
    principles: [
      { number: '01', title: 'Rendre la complexité fluide.', copy: 'J’apprécie les systèmes robustes en profondeur et simples à utiliser.' },
      { number: '02', title: 'Construire pour le réel.', copy: 'Un logiciel utile s’adapte à des exigences changeantes, à des données imparfaites et à la pression de la production.' },
      { number: '03', title: 'S’investir au-delà de la livraison.', copy: 'La qualité n’est pas une finition. Elle guide la conception, la livraison et la maintenance du produit.' },
    ],
    capabilities: ['Architecture', 'Encadrement d’équipe', 'Chiffrage de projets', 'Revues de merge requests', 'Communication client', 'Intégrations de paiement'],
    skillGroups: [
      { label: 'Backend', items: shared.tags.backend },
      { label: 'Frontend & mobile', items: shared.tags.frontend },
      { label: 'Bases de données & outillage', items: shared.tags.delivery },
      { label: 'Architecture & intégration', items: shared.tags.architecture },
    ],
    education: [
      { year: '2018 — 2020', degree: 'Master spécialisé · Ingénierie des systèmes d’information', school: 'Faculté des Sciences Semlalia · Université Cadi Ayyad, Marrakech' },
      { year: '2017 — 2018', degree: 'Licence professionnelle · Informatique', school: 'École Supérieure de Technologie · Université Mohammed Ier, Oujda' },
      { year: '2015 — 2017', degree: 'DUT · Développement d’applications informatiques', school: 'École Supérieure de Technologie · Université Mohammed Ier, Oujda' },
    ],
    community: [
      { name: 'ForLoop Africa', role: 'Co-organisateur', period: '2018 — 2022' },
      { name: 'Enactus', role: 'Membre', period: '2015 — 2018' },
    ],
    lab: {
      label: 'Lab de Tech Lead',
      eyebrow: 'Les décisions en mouvement',
      title: 'Transformer l’ambiguïté en trajectoire de livraison.',
      intro: 'Des parcours de décision interactifs inspirés du travail qui précède le code : cadrer les risques, choisir les bonnes frontières, aligner les équipes et livrer progressivement.',
      status: 'Scénario interactif',
      run: 'Lancer le parcours',
      decisionLabel: 'Décision d’architecture',
      tradeoffLabel: 'Compromis',
      leadMoveLabel: 'Action du Tech Lead',
      scenarios: [
        {
          id: 'payments',
          tab: 'Orchestration du paiement',
          title: 'Concevoir un parcours de paiement résilient',
          brief: 'Ajouter le paiement en une fois, en 2 fois et en 4 fois sans coupler le tunnel de commande à chaque prestataire.',
          nodes: ['B2C / B2B', 'Commande', 'Contrat de paiement', 'Monext / FLOA', 'Commande confirmée'],
          decision: 'Isoler la logique propre à chaque prestataire derrière un contrat stable d’orchestration du paiement.',
          tradeoff: 'Davantage de travail d’intégration au départ, mais les changements de prestataire et la gestion des échecs restent contenus.',
          leadMove: 'Aligner produit, sécurité, finance et ingénierie sur les scénarios de relance, d’annulation et de remboursement avant l’implémentation.',
        },
        {
          id: 'modernization',
          tab: 'Modernisation du legacy',
          title: 'Moderniser sans mettre le revenu en risque',
          brief: 'Faire évoluer des plateformes touristiques matures tout en préservant les comportements métier et les intégrations critiques.',
          nodes: ['Parcours legacy', 'API de compatibilité', 'Interface moderne', 'Services métier', 'Déploiement progressif'],
          decision: 'Moderniser parcours par parcours avec des frontières de compatibilité claires, plutôt que lancer une réécriture risquée.',
          tradeoff: 'La coexistence temporaire ajoute de la complexité ; les contrats, le suivi et la responsabilité la rendent maîtrisable.',
          leadMove: 'Séquencer les lots, définir les responsabilités et protéger la continuité métier avec des jalons de déploiement explicites.',
        },
        {
          id: 'teams',
          tab: 'Livraison multi-équipe',
          title: 'Aligner 5 à 15 ingénieurs',
          brief: 'Transformer un chiffrage et une architecture en travaux parallèles sans perdre la cohérence technique.',
          nodes: ['Besoin produit', 'Décision tracée', 'Responsabilité équipe', 'Revue technique', 'Livraison progressive'],
          decision: 'Exprimer l’architecture sous forme de frontières, de contrats et de responsabilités permettant aux équipes d’avancer de manière autonome.',
          tradeoff: 'L’alignement initial prend du temps, mais réduit les reprises, les blocages en revue et les surprises entre équipes.',
          leadMove: 'Fixer les standards de revue, déléguer les décisions locales, suivre les dépendances et raccourcir les boucles de retour.',
        },
      ],
      ai: {
        mark: 'IA',
        eyebrow: 'Ingénierie assistée par l’IA',
        title: 'Garder le leadership humain tout en mettant l’IA au travail.',
        copy: 'Je me tiens à jour sur des outils comme OpenAI Codex et Claude pour explorer des options d’architecture, accélérer la documentation, préparer les revues et réduire les tâches répétitives. Leurs résultats restent soumis au contexte du système, aux contrôles de sécurité, aux tests et au jugement humain.',
        tags: ['OpenAI Codex', 'Claude', 'Exploration d’architecture', 'Assistance aux revues', 'Documentation'],
      },
    },
    contact: {
      orbit: 'ÉCHANGEONS · CONSTRUISONS · ÉCHANGEONS ·', eyebrow: 'La prochaine bonne conversation',
      titleBefore: 'Vous avez quelque chose', titleAccent: 'd’intéressant', titleAfter: 'en tête ?',
      copy: 'Parlez-moi du problème que vous souhaitez résoudre, de l’équipe que vous construisez, ou dites-moi simplement bonjour.',
      linkedin: 'Me contacter sur LinkedIn', email: 'M’écrire',
    },
    footer: { statementOne: 'Une ingénierie réfléchie.', statementTwo: 'Des produits fiables.', backToTop: 'Retour en haut ↑' },
  },
} as const
